"""primer_intento_equipo

Revision ID: 44635de709fc
Revises: 
Create Date: 2024-08-09 21:25:28.635786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44635de709fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'equipo', ['equipo_id'], ['id'])

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'equipo', ['equipo_id'], ['id'])

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabricante_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'fabricante', ['fabricante_id'], ['id'])

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('persona_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('producto')
        batch_op.drop_column('condicion_iva_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condicion_iva_id', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('producto', mysql.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('persona_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fabricante_id')

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipo_id')

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipo_id')

    op.drop_table('categoria')
    # ### end Alembic commands ###
