"""actualizacion_caracteristicas_accesorios

Revision ID: 46322b541eda
Revises: a8876a65472f
Create Date: 2024-08-02 19:11:01.827736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46322b541eda'
down_revision = 'a8876a65472f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'equipo', ['equipo_id'], ['id'])

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'equipo', ['equipo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipo_id')

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipo_id')

    # ### end Alembic commands ###
