"""Agregar equipo_id a Stock

Revision ID: a8876a65472f
Revises: 16bdfeded086
Create Date: 2024-07-30 20:28:37.301227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8876a65472f'
down_revision = '16bdfeded086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'equipo', ['equipo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipo_id')

    # ### end Alembic commands ###
