"""marcamodeloproveedor

Revision ID: eab7dec30fe4
Revises: 0bb301474246
Create Date: 2024-08-06 20:22:48.808582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eab7dec30fe4'
down_revision = '0bb301474246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condicion_iva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razon_social', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mail', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cuit', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('condicion_iva_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('producto', sa.String(length=20), nullable=False))
        batch_op.drop_column('contacto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacto', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('producto')
        batch_op.drop_column('condicion_iva_id')
        batch_op.drop_column('cuit')
        batch_op.drop_column('mail')
        batch_op.drop_column('razon_social')

    op.drop_table('producto')
    op.drop_table('condicion_iva')
    # ### end Alembic commands ###
